package org.data.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import lombok.Generated;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName("data_source_config")
public class DataSourceConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.ID
     *
     * @mbg.generated
     */
    @TableField(value = "id")
    @TableId(type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.DATA_SOURCE_KEY
     *
     * @mbg.generated
     */
    private String dataSourceKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.PASSWORD
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.DRIVER_CLASS_NAME
     *
     * @mbg.generated
     */
    private String driverClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.CREATE_USER
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.UPDATE_USER
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source_config.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;
}