package org.data.mapper;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import org.data.model.DataTransConfig;

@Mapper
public interface DataTransConfigMapper extends BaseMapper<DataTransConfig> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_trans_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_trans_config
     *
     * @mbg.generated
     */
    int insert(DataTransConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_trans_config
     *
     * @mbg.generated
     */
    DataTransConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_trans_config
     *
     * @mbg.generated
     */
    List<DataTransConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_trans_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataTransConfig record);
}