package org.data.mapper;

import java.util.List;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;
import org.data.model.DataSourceConfig;

@Mapper
public interface DataSourceConfigMapper extends BaseMapper<DataSourceConfig> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source_config
     *
     * @mbg.generated
     */
    int insert(DataSourceConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source_config
     *
     * @mbg.generated
     */
    DataSourceConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source_config
     *
     * @mbg.generated
     */
    List<DataSourceConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataSourceConfig record);
}